sonar.projectKey=OpenAfterHours_rwa_calculator
sonar.organization=openafterhours
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=python:S101
sonar.issue.ignore.multicriteria.e1.resourceKey=tests/**/*.py
