"""Regenerate ``docs/development/citation-matrix.md`` from live ``@cites`` annotations.

Invokes ``watchfire matrix --format markdown`` once per indexed instrument
(CRR, PS1/26) and stitches the rendered tables into a single docs page
with a short preamble. Intended to be run by hand after annotation
changes, or wired into CI on push-to-master.

Usage:
    uv run python scripts/generate_citation_matrix.py

Exit codes:
    0 = matrix regenerated successfully
    1 = watchfire matrix invocation failed
"""

from __future__ import annotations

import subprocess
import sys
from datetime import date
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATH = REPO_ROOT / "docs" / "development" / "citation-matrix.md"


PREAMBLE = """# Citation Coverage Matrix

This page is generated by ``scripts/generate_citation_matrix.py`` from the
live ``@cites(...)`` decorators in ``src/rwa_calc/``. Each row maps a
regulatory article to the engine function(s) that implement it. See
[citation-tracking.md](citation-tracking.md) for the conventions and
canonical citation grammar.

Regenerate after annotation changes:

```bash
uv run python scripts/generate_citation_matrix.py
```

Last generated: {generated_on}.

"""


def _run_matrix(instrument: str) -> str:
    """Invoke ``watchfire matrix --instrument <X> --format markdown``."""
    result = subprocess.run(
        [
            "uv",
            "run",
            "watchfire",
            "matrix",
            "--instrument",
            instrument,
            "--format",
            "markdown",
        ],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        sys.stderr.write(
            f"watchfire matrix --instrument {instrument} exited "
            f"{result.returncode}\n{result.stderr}\n"
        )
        sys.exit(1)
    return result.stdout.rstrip() + "\n"


def main() -> int:
    crr_table = _run_matrix("CRR")
    ps_table = _run_matrix("PS")

    body = (
        PREAMBLE.format(generated_on=date.today().isoformat())
        + "## CRR (Capital Requirements Regulation)\n\n"
        + crr_table
        + "\n## PS1/26 (PRA Policy Statement)\n\n"
        + ps_table
    )

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(body, encoding="utf-8")
    print(f"wrote {OUTPUT_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
